name: Daily Docker Build and Publish

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  release:
    uses: batinicaz/gha/.github/workflows/docker.yml@latest
    secrets:
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
